### ISSUE TITLE
Patchwork review issues

### ISSUE THREAD

**Issue by tilgovi** [mattaitchison/entrykit-apk#1]
http://patchwork.alpinelinux.org/patch/1779/

I put amd64 because I didn't know enough about go and aports to know whether the resulting package would be portable. @andyshinn do you have insight that applies here?

@mattaitchison I'll try to do the rest. I assume I just need to recreate the hash and I'll change the pkgrel in a PR.

**Comment by andyshinn** [comment]
Do you have the cycles to spin up a Scaleway instance and x86 VM to test compiling?

**Comment by tilgovi** [comment]
@andyshinn I was more asking whether there is a particular pattern you know to work for writing 32/64-bit APKs. I can find cycles to test but the more cycles I can avoid figuring out what _should_ work the better.

**Comment by andyshinn** [comment]
I'm not quite sure. Unless the code is specifically written for 64bit, I don't see why it wouldn't compile o arm or 32bit.

**Comment by tilgovi** [comment]
I had a lapse of understanding, confusing `noarch` and `all`. It should be fine as `all`. PR open to fix all these issues.
